apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-video-factory-dev

resources:
  - ../../base

namePrefix: dev-

# Lower resource requests for dev environment
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
