/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@ai-video-factory/shared-types$': '<rootDir>/packages/shared-types/src',
    '^@ai-video-factory/prompt-library$': '<rootDir>/packages/prompt-library/src',
    '^@ai-video-factory/knowledge-sdk$': '<rootDir>/packages/knowledge-sdk/src',
    '^@ai-video-factory/workflow-sdk$': '<rootDir>/packages/workflow-sdk/src',
    '^@ai-video-factory/storage-sdk$': '<rootDir>/packages/storage-sdk/src',
    '^@ai-video-factory/db$': '<rootDir>/packages/db/src',
    '^@ai-video-factory/analysis-service$': '<rootDir>/services/analysis-service/src',
    '^@ai-video-factory/script-service$': '<rootDir>/services/script-service/src',
    '^@ai-video-factory/content-service$': '<rootDir>/services/content-service/src',
    '^@ai-video-factory/media-service$': '<rootDir>/services/media-service/src',
    '^@ai-video-factory/subtitle-service$': '<rootDir>/services/subtitle-service/src',
    '^@ai-video-factory/render-service$': '<rootDir>/services/render-service/src',
    '^@ai-video-factory/trend-service$': '<rootDir>/services/trend-service/src',
  },
  testTimeout: 15000,
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: {
        target: 'ES2022',
        lib: ['ES2022'],
        module: 'commonjs',
        esModuleInterop: true,
        strict: true,
        skipLibCheck: true,
        paths: {
          '@ai-video-factory/shared-types': ['packages/shared-types/src'],
          '@ai-video-factory/prompt-library': ['packages/prompt-library/src'],
          '@ai-video-factory/knowledge-sdk': ['packages/knowledge-sdk/src'],
          '@ai-video-factory/workflow-sdk': ['packages/workflow-sdk/src'],
          '@ai-video-factory/storage-sdk': ['packages/storage-sdk/src'],
          '@ai-video-factory/db': ['packages/db/src'],
          '@ai-video-factory/analysis-service': ['services/analysis-service/src'],
          '@ai-video-factory/script-service': ['services/script-service/src'],
          '@ai-video-factory/content-service': ['services/content-service/src'],
          '@ai-video-factory/media-service': ['services/media-service/src'],
          '@ai-video-factory/subtitle-service': ['services/subtitle-service/src'],
          '@ai-video-factory/render-service': ['services/render-service/src'],
          '@ai-video-factory/trend-service': ['services/trend-service/src'],
        },
      },
    }],
  },
};
